name: Deploy to Two Servers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build image 
        run: docker buildx build --no-chache -t registry.alvaro.studentdumbways.my.id/ntx-test/ntx:latest .

      - name: Login to Docker Hub
        run: | 
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.example.com -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          
